In [258]:
#pip install contractions emoji autocorrect nltk 
import nltk
import string
import re

In [259]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\samya.taqi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

# Text Normalisation

In [260]:
def text_lowercase(text):
    return text.lower()

In [261]:
input_text="Hey, did you know that the summer break is coming? Amazing right !! It's only 5 more days !!"
text_lowercase(input_text)

"hey, did you know that the summer break is coming? amazing right !! it's only 5 more days !!"

In [262]:
import contractions  # cette bibliothéque sert à developper les contractions anglais I'm  devient  I m

def fix_cotractions (data):
    expanded_corpus= [ contractions.fix(text)for text in data]
    return expanded_corpus

In [263]:
corpus= [
    "I can't wait for the new season of my favorate show!"
    "Lemme know when you're ready.",
    "Let's go!",
    "Nothing gonna change my love for you"
]

In [264]:
fix_cotractions(corpus)

['I cannot wait for the new season of my favorate show!Let Me know when you are ready.',
 'Let us go!',
 'Nothing going to change my love for you']

**en français**

In [265]:
import re

contractions_fr = {
    "j'": "je ",
    "t'": "te ",
    "c'": "ce ",
    "d'": "de ",
    "l'": "le ",
    "qu'": "que ",
    "n'": "ne ",
    "s'": "se "
}

def fix_contractions_fr(text):
    for contr, full in contractions_fr.items():
        text = re.sub(rf"\b{contr}", full, text)
    return text

# Exemple
text = "J'aime le chocolat et c'est délicieux."
print(fix_contractions_fr(text))

J'aime le chocolat et ce est délicieux.

In [266]:
#spell cheking

from autocorrect import Speller
def correct_with_autocorrect(text, lang='en'):
    """Correct spelling using autocorrect library for English."""
    spell=Speller(lang=lang)
    return spell(text)

In [267]:
#Exemple
text="I wnt to the librry to reed a bok."
corrected=correct_with_autocorrect(text)
print(f"Original: {text}")
print(f"Corrected: {corrected}")

Original: I wnt to the librry to reed a bok.
Corrected: I wnt to the library to reed a bok.

In [268]:
text="I'm not sleapy and tehre is no place I'm giong to."
corrected=correct_with_autocorrect(text)
print(f"Original: {text}")
print(f"Corrected: {corrected}")

Original: I'm not sleapy and tehre is no place I'm giong to.
Corrected: I'm not sleepy and there is no place I'm going to.

In [269]:
from textblob import TextBlob

def correct_with_textblob(text):
    blob=TextBlob(text)
    corrected=blob.correct()
    return str(corrected)

text="I wnt to the librry to reed a bok."
corrected=correct_with_textblob(text)
print(f"Original: {text}")
print(f"Corrected: {corrected}")

Original: I wnt to the librry to reed a bok.
Corrected: I went to the library to reed a boy.

In [270]:
import language_tool_python


tool = language_tool_python.LanguageTool('en-US')  # Correcteur anglais

text = "I wnt to the librry to reed a bok."
matches = tool.check(text)
corrected = language_tool_python.utils.correct(text, matches)

print("Original:", text)
print("Corrected:", corrected)

SystemError: Detected java 1.8. LanguageTool requires Java >= 17 for version latest.

# Standardising accent characters

In [ ]:
import unicodedata

def standardize_acceted_chars(text):
    return unicodedata.normalize('NFKD',text).encode('ascii','ignore').decode('utf-8', 'ignore')

In [ ]:
input_text= 'Sómě words as résumé, café ,prótest, divorcé , cordinate, exposé , latté .'
print(standardize_acceted_chars(input_text))

Some words as resume, cafe ,protest, divorce , coordinate, expose , latte .

In [ ]:
def remove_html_tags_regex(text):
    """Remove HTML tags using regular expression."""
    clean= re.compile('<.*?>')
    return re.sub(clean, '',text)

In [ ]:
html_text="<p>Hello , <b>world</b>!</p> <a href='#'>Click here</a>"
clean_text= remove_html_tags_regex(html_text)
print(clean_text)

Hello , world! Click here

In [ ]:
#removing numbers/digits

def remove_numbers(text):
    result=re.sub(r'\d{7,}', '<phone number>', text)
    return result

In [ ]:
input_text="Her phone number is 0123456789, and my phone number is 0987654321. He has 300 dollars."
remove_numbers(input_text)

'Her phone number is <phone number>, and my phone number is <phone number>. He has 300 dollars.'

**convert the numbers into words**

In [ ]:
import inflect
p=inflect.engine()
#CONVERTIE LE NUMERO EN MOTS
def convert_numbre(text):
    #SPLIT STRING INTO LIST OF WORDS 
    temp_str=text.split()
    # initialiser une liste vide 
    new_string=[]
    for word in temp_str:
        # if le mot is a digit, convertie the digit
        if word.isdigit():
            temp=p.number_to_words(word)
            new_string.append(temp)
            #appeler le mot as it is
        else:
            new_string.append(word)
            #join the words of new_string to form a string
    temp_str= ' '.join(new_string)
    return temp_str
input_text= 'There are 3 balls in this bag, and 12 in the other one.'
convert_numbre(input_text)

'There are three balls in this bag, and twelve in the other one.'

In [ ]:
regular_punct=list(string.punctuation)
print(regular_punct)

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

In [ ]:
def remove_punctuation(text, punct_text):
    for punc in punct_text:
        if punc in text:
            text=text.replace(punc, ' ')
    return text.strip()

remove_punctuation("Hey @Lisa, did you know thet the summer break is coming? Amazing right !! It's only 5 more days !!", regular_punct)

'Hey  Lisa  did you know thet the summer break is coming  Amazing right    It s only 5 more days'

In [ ]:
# manipuler double whitespace from text

def remove_whitespace(text):
    return " ".join(text.split())

input_str="We don't need the given      questions"
remove_whitespace(input_str)

"We don't need the given questions"

In [ ]:
# gérer emoji/emoticon pour analyser sentiment 
def remove_emojis_regex(text):
    """Remove emojis using Unicode emoji ranges."""
    #unicode ranges for emojis
    emoji_pattern= re.compile("["
                              u"\U0001F600-\U0001F64F"
                              u"\U0001F300-\U0001F5FF"
                              u"\U0001F680-\U0001F6FF"
                              u"\U0001F1E0-\U0001F1FF"
                              u"\U00002702-\U000027B0"
                              u"\U000024C2-\U0001F251"
                              u"\U0001f926-\U0001f937"
                              u"\U00010000-\U0010ffff"
                                "]+", flags=re.UNICODE)
    
    return emoji_pattern.sub(r'', text)

In [ ]:
text="Hello! How are yo?🙂​ I'm in NYC"
clean_text=remove_emojis_regex(text)
print(clean_text)

Hello! How are yo?​ I'm in NYC

In [ ]:
import emoji

def remove_emojis_emoji_library(text):
    """Remove emojis using the emoji library."""
    return emoji.replace_emoji(text, replace='')

def replace_emojis_with_text(text):
    """Replace emojis with their text descriptions using the emoji library"""
    return emoji.demojize(text)
 
text="Hello! 😊👋 how are you? i'm in Morrocco ❤️ "
print(remove_emojis_emoji_library(text))
print(replace_emojis_with_text(text))

Hello!  how are you? i'm in Morrocco
Hello! :smiling_face_with_smiling_eyes::waving_hand: how are you? i'm in Morrocco :red_heart:

In [ ]:
url_pattern=re.compile(r'https://\S+')
def remove_url(text):
    return url_pattern.sub('', text)
text="Visit https://www.google.com for more information."
remove_url(text)

'Visit  for more information.'

In [ ]:
url_pattern=[]
url_pattern.append(re.compile(r'https:?//\S+'))
url_pattern.append(re.compile(r'http:?//\S+'))
url_pattern.append(re.compile(r'www.\S+'))

def remove_urls2(text):
    for pattern in url_pattern:
        text=pattern.sub('<this link>', text)
    return text

input_text="Visite the folowing link: www.google.com"
print(remove_urls2(input_text))

Visite the folowing link: <this link>

# Tokenization

In [ ]:
#nltk.downoald('pukt_tab') this line is needed to télécharger the necessary datasets for tokenization
text="This is a text to tokenize"
tokenized=nltk.word_tokenize(text)

print("Result from tokenization", tokenized)

Result from tokenization ['This', 'is', 'a', 'text', 'to', 'tokenize']

# stopwords removal

In [ ]:
from nltk.corpus import stopwords 
nltk.download('stopwords')

stop_words=set(stopwords.words('english'))

print(stop_words)

{'haven', "he'll", 'here', 'under', 'before', 'aren', 'other', 'from', 'hadn', 'hasn', 'was', 'during', 'its', 'those', 'shouldn', 'be', "they're", 'himself', 'mustn', 'why', "you'd", 'such', 'where', 'have', 'at', 'his', 'is', "wouldn't", 'can', "we'd", 'until', 'so', 'should', "you're", 've', "i'd", 'as', 'd', "she'll", 'isn', 'this', 'more', 'by', 'out', 'now', 'they', "wasn't", 'won', 'some', "i'm", "she'd", 't', 'theirs', 'about', 'y', 'm', 'don', 'being', 'a', 'mightn', 'their', 'needn', 'to', 'below', 'am', 'ma', 'does', "isn't", "you'll", 'nor', 'each', "i've", "they'll", 'i', "hadn't", 'these', 'and', 'yourselves', 'ourselves', 'yourself', 'with', 'that', "he'd", "he's", "that'll", 'into', "should've", "shan't", 'has', "i'll", 'your', "aren't", 'not', 'shan', 'me', 'do', 'myself', 'the', 'own', 'because', 'him', 'my', 'herself', 'o', 'ours', "it'd", 'itself', 'down', "she's", 'up', "weren't", 'themselves', 'wouldn', 'than', "doesn't", 'any', 'them', "they've", 'will', 'didn', "they'd", 'ain', 'in', 'through', 'between', 'what', 'were', 'all', "didn't", 'wasn', 'weren', 'very', "mightn't", 'or', "we've", 'which', "couldn't", 's', "shouldn't", 'then', 'she', 'you', 'having', 'further', 'off', 'most', "hasn't", 'over', 'against', 'doesn', 'same', "it'll", 'couldn', 'he', 'whom', 'if', 'of', 'after', "you've", "won't", "needn't", 'her', 'on', 'but', 'are', "it's", 'when', "mustn't", 'both', "don't", "we're", 'had', 'few', "we'll", 'once', 'we', 'only', 'yours', 'been', 'll', 're', 'no', 'there', 'while', 'our', 'again', 'just', 'how', 'did', 'an', 'doing', 'above', 'too', "haven't", 'for', 'who', 'it', 'hers'}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\samya.taqi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
stop_words_fr=set(stopwords.words('french'))
print(stop_words_fr)

{'sont', 'et', 'étante', 'fut', 'ne', 'ses', 'étants', 'vous', 'furent', 'ayantes', 'j', 'aie', 'été', 'nous', 'serai', 'avez', 'des', 'nos', 'ton', 'fus', 'as', 'd', 'auraient', 'aurez', 'serez', 'auriez', 'aux', 'eue', 'eûmes', 't', 'seraient', 'y', 'serait', 'm', 'avons', 'es', 'seriez', 'soyez', 'ma', 'je', 'se', 'étiez', 'votre', 'avec', 'eux', 'aient', 'serons', 'que', 'ces', 'étais', 'aviez', 'étant', 'serais', 'aura', 'avais', 'son', 'fûtes', 'n', 'eûtes', 'la', 'ta', 'eurent', 'les', 'me', 'du', 'c', 'fusses', 'avaient', 'eussent', 'en', 'seras', 'aurons', 'ou', 'eussiez', 'eus', 'même', 'notre', 'lui', 'ont', 'aurions', 'le', 'étés', 'étaient', 'aies', 'qu', 'ai', 'il', 'eu', 'était', 'serions', 'au', 'elle', 'pour', 'eusses', 'pas', 'eût', 'fût', 'une', 'ayante', 'par', 'ait', 'eut', 'mais', 'soit', 's', 'aurai', 'êtes', 'de', 'avait', 'aurais', 'eusse', 'ayant', 'ayants', 'eussions', 'fussent', 'moi', 'soyons', 'te', 'sera', 'étées', 'toi', 'l', 'à', 'étée', 'sois', 'on', 'mon', 'soient', 'qui', 'ils', 'suis', 'auras', 'sur', 'ayons', 'un', 'auront', 'avions', 'ayez', 'étions', 'tes', 'fussiez', 'vos', 'fussions', 'tu', 'fusse', 'eues', 'est', 'étantes', 'aurait', 'ce', 'seront', 'leur', 'sa', 'dans', 'mes', 'sommes', 'fûmes'}

In [ ]:
stop_words.add('test')
print(stop_words)

{'haven', "he'll", 'here', 'under', 'before', 'aren', 'other', 'from', 'hadn', 'hasn', 'was', 'during', 'its', 'those', 'shouldn', 'be', "they're", 'himself', 'mustn', 'why', "you'd", 'such', 'where', 'have', 'at', 'his', 'is', "wouldn't", 'can', "we'd", 'until', 'so', 'should', "you're", 've', "i'd", 'as', 'd', "she'll", 'isn', 'this', 'more', 'by', 'out', 'now', 'they', "wasn't", 'won', 'some', "i'm", "she'd", 't', 'theirs', 'about', 'y', 'm', 'don', 'being', 'a', 'mightn', 'their', 'needn', 'to', 'below', 'am', 'ma', 'does', "isn't", "you'll", 'nor', 'each', "i've", "they'll", 'i', "hadn't", 'these', 'and', 'yourselves', 'ourselves', 'yourself', 'with', 'that', "he'd", "he's", "that'll", 'into', "should've", "shan't", 'has', "i'll", 'your', "aren't", 'not', 'shan', 'me', 'do', 'myself', 'the', 'own', 'because', 'him', 'my', 'herself', 'o', 'ours', "it'd", 'itself', 'down', "she's", 'up', "weren't", 'themselves', 'wouldn', 'than', "doesn't", 'any', 'them', "they've", 'will', 'didn', "they'd", 'ain', 'in', 'through', 'between', 'what', 'were', 'all', "didn't", 'wasn', 'weren', 'very', "mightn't", 'or', "we've", 'which', "couldn't", 's', 'test', "shouldn't", 'then', 'she', 'you', 'having', 'further', 'off', 'most', "hasn't", 'over', 'against', 'doesn', 'same', "it'll", 'couldn', 'he', 'whom', 'if', 'of', 'after', "you've", "won't", "needn't", 'her', 'on', 'but', 'are', "it's", 'when', "mustn't", 'both', "don't", "we're", 'had', 'few', "we'll", 'once', 'we', 'only', 'yours', 'been', 'll', 're', 'no', 'there', 'while', 'our', 'again', 'just', 'how', 'did', 'an', 'doing', 'above', 'too', "haven't", 'for', 'who', 'it', 'hers'}

In [ ]:
# the required libraries
from nltk.tokenize import word_tokenize
from nltk.tokenize import word_tokenize

def remove_stopwords(text):
    stop_words=set(stopwords.words("english"))
    word_tokens= word_tokenize(text)

    filtred_text=[word for word in word_tokens if word.lower() not in stop_words]
    return filtred_text 


exemple_text="This is a sample sentence and we are going to remove the stopwords from this."

print("Before removing stopwords:", exemple_text)
print("After removieng stopwords", remove_stopwords(exemple_text))

Before removing stopwords: This is a sample sentence and we are going to remove the stopwords from this very.
After removieng stopwords ['sample', 'sentence', 'going', 'remove', 'stopwords', '.']

**porte stemmer algorithm**

In [ ]:
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer= PorterStemmer()
def stem_words(text):
    word_tokens= word_tokenize(text)
    stems= [stemmer.stem(word) for word in word_tokens]
    return stems

text="data science uses scientific methods algorithms and many types of processes"
stem_words(text)

['data',
 'scienc',
 'use',
 'scientif',
 'method',
 'algorithm',
 'and',
 'mani',
 'type',
 'of',
 'process']

In [ ]:
#lemmatization using nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer= WordNetLemmatizer()

def lemma_words(text):
    words_tokens=word_tokenize(text)
    lemmas=[lemmatizer.lemmatize(word) for word in words_tokens]
    return lemmas

text='The quick brown foxes are jumping over the lazy dogs.'
print(lemma_words(text))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\samya.taqi\AppData\Roaming\nltk_data...

['The', 'quick', 'brown', 'fox', 'are', 'jumping', 'over', 'the', 'lazy', 'dog', '.']

In [ ]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 14.9 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 45.4 MB/s  0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import spacy

nlp=spacy.load('en_core_web_sm')

In [ ]:
text='The quick brown foxes are jumping over the lazy dogs.'
doc=nlp(text)

lemmatized_text=[token.lemma_ for token in doc]
lemmatized_text= ' '.join(lemmatized_text)

print("Original: ", text)
print("Lemmatized Text: ", lemmatized_text)

Original:  The quick brown foxes are jumping over the lazy dogs.
Lemmatized Text:  the quick brown fox be jump over the lazy dog .

In [ ]:
import pandas as pd

df = pd.read_csv("data\SMS_test.csv", encoding="windows-1252", sep=',')
df

<>:3: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
C:\Users\samya.taqi\AppData\Local\Temp\ipykernel_10928\733879312.py:3: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv("data\SMS_test.csv", encoding="windows-1252", sep=',')

     S. No.                                       Message_body     Label
0         1  UpgrdCentre Orange customer, you may now claim...      Spam
1         2  Loan for any purpose £500 - £75,000. Homeowner...      Spam
2         3  Congrats! Nokia 3650 video camera phone is you...      Spam
3         4  URGENT! Your Mobile number has been awarded wi...      Spam
4         5  Someone has contacted our dating service and e...      Spam
..      ...                                                ...       ...
120     121  7 wonders in My WORLD 7th You 6th Ur style 5th...  Non-Spam
121     122  Try to do something dear. You read something f...  Non-Spam
122     123  Sun ah... Thk mayb can if dun have anythin on....  Non-Spam
123     124  SYMPTOMS when U are in love: "1.U like listeni...  Non-Spam
124     125  Great. Have a safe trip. Dont panic surrender ...  Non-Spam

[125 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S. No.        125 non-null    int64
 1   Message_body  125 non-null    str
 2   Label         125 non-null    str
dtypes: int64(1), str(2)
memory usage: 3.1 KB

In [ ]:
df.describe()

           S. No.
count  125.000000
mean    63.000000
std     36.228442
min      1.000000
25%     32.000000
50%     63.000000
75%     94.000000
max    125.000000

In [ ]:
def normalize_text(text):
    return text.lower()

In [ ]:
df["message_clean"]=df["Message_body"].apply(normalize_text)
df

,S. No.,Message_body,Label,message_clean
0,1,"UpgrdCentre Orange customer, you may now claim...",Spam,"upgrdcentre orange customer, you may now claim..."
1,2,"Loan for any purpose £500 - £75,000. Homeowner...",Spam,"loan for any purpose £500 - £75,000. homeowner..."
2,3,Congrats! Nokia 3650 video camera phone is you...,Spam,congrats! nokia 3650 video camera phone is you...
3,4,URGENT! Your Mobile number has been awarded wi...,Spam,urgent! your mobile number has been awarded wi...
4,5,Someone has contacted our dating service and e...,Spam,someone has contacted our dating service and e...
...,...,...,...,...
120,121,7 wonders in My WORLD 7th You 6th Ur style 5th...,Non-Spam,7 wonders in my world 7th you 6th ur style 5th...
121,122,Try to do something dear. You read something f...,Non-Spam,try to do something dear. you read something f...
122,123,Sun ah... Thk mayb can if dun have anythin on....,Non-Spam,sun ah... thk mayb can if dun have anythin on....
123,124,"SYMPTOMS when U are in love: ""1.U like listeni...",Non-Spam,"symptoms when u are in love: ""1.u like listeni..."
124,125,Great. Have a safe trip. Dont panic surrender ...,Non-Spam,great. have a safe trip. dont panic surrender ...

In [ ]:
df=df.drop("Message_body" , axis=1)
df

     S. No.     Label                                      message_clean
0         1      Spam  upgrdcentre orange customer, you may now claim...
1         2      Spam  loan for any purpose £500 - £75,000. homeowner...
2         3      Spam  congrats! nokia 3650 video camera phone is you...
3         4      Spam  urgent! your mobile number has been awarded wi...
4         5      Spam  someone has contacted our dating service and e...
..      ...       ...                                                ...
120     121  Non-Spam  7 wonders in my world 7th you 6th ur style 5th...
121     122  Non-Spam  try to do something dear. you read something f...
122     123  Non-Spam  sun ah... thk mayb can if dun have anythin on....
123     124  Non-Spam  symptoms when u are in love: "1.u like listeni...
124     125  Non-Spam  great. have a safe trip. dont panic surrender ...

[125 rows x 3 columns]

In [ ]:
message=df["message_clean"]
message

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th ur style 5th...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when u are in love: "1.u like listeni...
124    great. have a safe trip. dont panic surrender ...
Name: message_clean, Length: 125, dtype: str

In [ ]:
def fix_contractions(text):
    return contractions.fix(text)

messages_no_contractions = message.apply(fix_contractions)
messages_no_contractions

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congrats! nokia 3650 video camera phone is you...
3      urgent! your mobile number has been awarded wi...
4      someone has contacted our dating service and e...
                             ...
120    7 wonders in my world 7th you 6th you are styl...
121    try to do something dear. you read something f...
122    sun ah... thk mayb can if dun have anythin on....
123    symptoms when you are in love: "1.you like lis...
124    great. have a safe trip. do not panic surrende...
Name: message_clean, Length: 125, dtype: str

In [271]:
def correct_with_autocorrect(text):
    blob=TextBlob(text)
    corrected=blob.correct()
    return str(corrected)

messages_autocorrect=messages_no_contractions.apply(correct_with_autocorrect)
messages_autocorrect

0      upgrdcentre orange customer, you may now claim...
1      loan for any purpose £500 - £75,000. homeowner...
2      congress! nikita 3650 video camera phone is yo...
3      urgent! your mobile number has been awarded wi...
4      someone has contracted our dating service and ...
                             ...
120    7 wonders in my world th you th you are style ...
121    try to do something dear. you read something f...
122    sun ah... the may can if dun have anything on....
123    symptoms when you are in love: "1.you like lis...
124    great. have a safe trip. do not panic surrende...
Name: message_clean, Length: 125, dtype: str

In [274]:
def noise_removal(text):
    text = re.sub(r'\d+','',text) #enlever les nombres
    text=re.sub(r'[^\w\s]','', text) # enlever ponctuation
    text=unicodedata.normalize('NFKD',text).encode('ascii','ignore').decode('utf-8', 'ignore')
    text=re.sub(r'\s+',' ' ,text).strip() 

    return 
message_noise_removal=messages_autocorrect.apply(noise_removal)
message_noise_removal

NameError: name 'unicodedata' is not defined